
POST http://localhost:3500/auth/signup 
content-type: application/json

{
    "email": "john@gmail.com",
    "password": "12345"
}

###

POST http://localhost:3500/auth/signin 
content-type: application/json

{
    "email": "john@gmail.com",
    "password": "12345"
}

###

GET http://localhost:3500/users/me
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiam9obkBnbWFpbC5jb20iLCJpYXQiOjE2OTU1ODk5OTMsImV4cCI6MTY5NTU5MDg5M30.BV7Kd9cKv9R2bRDc_TFbRlWw4cg-gSnzy_XYTQ0gCsI