POST http://localhost:3500/auth/signin HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

###

POST http://localhost:3500/auth/signin 
content-type: application/json

{
    "email": "john@gmail.com",
    "password": "12345"
}


###

POST http://localhost:3500/auth/signup 
content-type: application/json

{
    "email": "john@gmail.com",
    "password": "12345"
}


###


GET http://localhost:3500/users/me
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiam9obkBnbWFpbC5jb20iLCJpYXQiOjE2OTU1ODczNDQsImV4cCI6MTY5NTU4ODI0NH0.tYcKgSC6eMDYMmVEnR9G509O0rXQk3TRmeKLXwbXYxQ